packages:
  - "glass-easel"
  - "glass-easel-miniprogram-adapter"
  - "glass-easel-miniprogram-webpack-plugin"
  - "glass-easel-shadow-sync"
  - "glass-easel-miniprogram-template"
  - "glass-easel-miniprogram-typescript"
  - "glass-easel-template-compiler"
  - "glass-easel-stylesheet-compiler"
